#!/bin/bash
# script to restart internet connection when it fails
# be sure to run this script with su permissions

pkill dhcpcd
pkill wpa_supllicant
sleep 5
wpa_supplicant -Dnl80211 -iwlp3s0 -c/etc/wpa_supplicant/wpa_supplicant.conf -B
dhcpcd wlp3s0

ping www.google.ca

# irq/43-iwlwifi
